### ISSUE TITLE
Python Timer & Direct skill connection 

### ISSUE THREAD

**Issue by Daniyaldehleh** [seattlecoderdojo/alexa-workshop#3]
HI @LetMyPeopleCode First of all, thank you for replying to my timer Api question on StackOverflow. We are very fortunate to have you as a multilingual Alexa developer. 

For the past couple of weeks, I have been able to translate the node.js documents & repos to create a sample timer API template for the Alexa python developers. However, translating the direct skill connection part of it has been **really** tough for me doing it all by myself. Even though, I have built the custom task, I keep on miserably failing to bond the timer API with the custom task. May I ask you if you could have a visit to my [repo](https://github.com/danieldhz/Alexa_Timer) for your guidance?

**Comment by LetMyPeopleCode** [comment]
You're commenting on a two-year-old document for a workshop from a STEM meetup I run. 

My python is old and rusty. I answer what questions I can, but this would require getting back up to speed with Python in a way I do not currently have the bandwidth to do. 

I suggest you take this to https://forums.developer.amazon.com/spaces/23/Alexa+Skills+Kit.html

**Comment by Daniyaldehleh** [comment]
Hi @LetMyPeopleCode!

I am sorry. I thought you are still flexible with the language. Is there anyone that you could possibly refer me to? As the majority of the questions, I ask on the forum go unanswered. As well as, do you know how we can keep the session open after calling a timer API?

**Comment by LetMyPeopleCode** [comment]
Go to Alexa Office Hours on Twitch (amazonalexa channel). There's one at 4 p.m. today and then next Tuesday at 9 a.m. Both times are Pacific. There's also an EU office hours usually featuring the IT and ES folks. It's all on the channel schedule. Can't guarantee an answer there, but besides the Alexa Evangelists running them, there are other devs who share their knowledge in chat.

**Comment by Daniyaldehleh** [comment]
Thank you for the timely response Greg!
I'll jump in right now :)
